language: python
python:
  - "3.6"
services:
  - postgresql  
install:
    - pip3 install -r requirements.txt
env:
  - DB=postgres
before_script:
  - psql -c "CREATE DATABASE hc;" -U postgres 
script:
  - coverage run --omit=*/tests/* --source=hc manage.py test
after_success: coveralls
cache: pip3

notifications:
    slack: andela:p2NDwUsBX7DhhxnvTSTVwLIT
